// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ProtonMail/export-tool/internal/apiclient (interfaces: Builder,Client,RetryStrategy)

// Package apiclient is a generated GoMock package.
package apiclient

import (
	context "context"
	io "io"
	reflect "reflect"

	proton "github.com/ProtonMail/go-proton-api"
	gomock "github.com/golang/mock/gomock"
)

// MockBuilder is a mock of Builder interface.
type MockBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockBuilderMockRecorder
}

// MockBuilderMockRecorder is the mock recorder for MockBuilder.
type MockBuilderMockRecorder struct {
	mock *MockBuilder
}

// NewMockBuilder creates a new mock instance.
func NewMockBuilder(ctrl *gomock.Controller) *MockBuilder {
	mock := &MockBuilder{ctrl: ctrl}
	mock.recorder = &MockBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBuilder) EXPECT() *MockBuilderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockBuilder) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockBuilderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockBuilder)(nil).Close))
}

// NewClient mocks base method.
func (m *MockBuilder) NewClient(arg0 context.Context, arg1 string, arg2 []byte, arg3 *proton.APIHVDetails) (Client, proton.Auth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewClient", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(Client)
	ret1, _ := ret[1].(proton.Auth)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// NewClient indicates an expected call of NewClient.
func (mr *MockBuilderMockRecorder) NewClient(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewClient", reflect.TypeOf((*MockBuilder)(nil).NewClient), arg0, arg1, arg2, arg3)
}

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Auth2FA mocks base method.
func (m *MockClient) Auth2FA(arg0 context.Context, arg1 proton.Auth2FAReq) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth2FA", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Auth2FA indicates an expected call of Auth2FA.
func (mr *MockClientMockRecorder) Auth2FA(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth2FA", reflect.TypeOf((*MockClient)(nil).Auth2FA), arg0, arg1)
}

// AuthDelete mocks base method.
func (m *MockClient) AuthDelete(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AuthDelete", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// AuthDelete indicates an expected call of AuthDelete.
func (mr *MockClientMockRecorder) AuthDelete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AuthDelete", reflect.TypeOf((*MockClient)(nil).AuthDelete), arg0)
}

// Close mocks base method.
func (m *MockClient) Close() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Close")
}

// Close indicates an expected call of Close.
func (mr *MockClientMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockClient)(nil).Close))
}

// CreateLabel mocks base method.
func (m *MockClient) CreateLabel(arg0 context.Context, arg1 proton.CreateLabelReq) (proton.Label, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateLabel", arg0, arg1)
	ret0, _ := ret[0].(proton.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateLabel indicates an expected call of CreateLabel.
func (mr *MockClientMockRecorder) CreateLabel(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateLabel", reflect.TypeOf((*MockClient)(nil).CreateLabel), arg0, arg1)
}

// GetAddresses mocks base method.
func (m *MockClient) GetAddresses(arg0 context.Context) ([]proton.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAddresses", arg0)
	ret0, _ := ret[0].([]proton.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAddresses indicates an expected call of GetAddresses.
func (mr *MockClientMockRecorder) GetAddresses(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAddresses", reflect.TypeOf((*MockClient)(nil).GetAddresses), arg0)
}

// GetAttachmentInto mocks base method.
func (m *MockClient) GetAttachmentInto(arg0 context.Context, arg1 string, arg2 io.ReaderFrom) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttachmentInto", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetAttachmentInto indicates an expected call of GetAttachmentInto.
func (mr *MockClientMockRecorder) GetAttachmentInto(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttachmentInto", reflect.TypeOf((*MockClient)(nil).GetAttachmentInto), arg0, arg1, arg2)
}

// GetGroupedMessageCount mocks base method.
func (m *MockClient) GetGroupedMessageCount(arg0 context.Context) ([]proton.MessageGroupCount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupedMessageCount", arg0)
	ret0, _ := ret[0].([]proton.MessageGroupCount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupedMessageCount indicates an expected call of GetGroupedMessageCount.
func (mr *MockClientMockRecorder) GetGroupedMessageCount(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupedMessageCount", reflect.TypeOf((*MockClient)(nil).GetGroupedMessageCount), arg0)
}

// GetLabels mocks base method.
func (m *MockClient) GetLabels(arg0 context.Context, arg1 ...proton.LabelType) ([]proton.Label, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetLabels", varargs...)
	ret0, _ := ret[0].([]proton.Label)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLabels indicates an expected call of GetLabels.
func (mr *MockClientMockRecorder) GetLabels(arg0 interface{}, arg1 ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLabels", reflect.TypeOf((*MockClient)(nil).GetLabels), varargs...)
}

// GetMessage mocks base method.
func (m *MockClient) GetMessage(arg0 context.Context, arg1 string) (proton.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", arg0, arg1)
	ret0, _ := ret[0].(proton.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockClientMockRecorder) GetMessage(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockClient)(nil).GetMessage), arg0, arg1)
}

// GetMessageMetadataPage mocks base method.
func (m *MockClient) GetMessageMetadataPage(arg0 context.Context, arg1, arg2 int, arg3 proton.MessageFilter) ([]proton.MessageMetadata, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessageMetadataPage", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]proton.MessageMetadata)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessageMetadataPage indicates an expected call of GetMessageMetadataPage.
func (mr *MockClientMockRecorder) GetMessageMetadataPage(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessageMetadataPage", reflect.TypeOf((*MockClient)(nil).GetMessageMetadataPage), arg0, arg1, arg2, arg3)
}

// GetSalts mocks base method.
func (m *MockClient) GetSalts(arg0 context.Context) (proton.Salts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalts", arg0)
	ret0, _ := ret[0].(proton.Salts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalts indicates an expected call of GetSalts.
func (mr *MockClientMockRecorder) GetSalts(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalts", reflect.TypeOf((*MockClient)(nil).GetSalts), arg0)
}

// GetUserWithHV mocks base method.
func (m *MockClient) GetUserWithHV(arg0 context.Context, arg1 *proton.APIHVDetails) (proton.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserWithHV", arg0, arg1)
	ret0, _ := ret[0].(proton.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserWithHV indicates an expected call of GetUserWithHV.
func (mr *MockClientMockRecorder) GetUserWithHV(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserWithHV", reflect.TypeOf((*MockClient)(nil).GetUserWithHV), arg0, arg1)
}

// MockRetryStrategy is a mock of RetryStrategy interface.
type MockRetryStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockRetryStrategyMockRecorder
}

// MockRetryStrategyMockRecorder is the mock recorder for MockRetryStrategy.
type MockRetryStrategyMockRecorder struct {
	mock *MockRetryStrategy
}

// NewMockRetryStrategy creates a new mock instance.
func NewMockRetryStrategy(ctrl *gomock.Controller) *MockRetryStrategy {
	mock := &MockRetryStrategy{ctrl: ctrl}
	mock.recorder = &MockRetryStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRetryStrategy) EXPECT() *MockRetryStrategyMockRecorder {
	return m.recorder
}

// HandleRetry mocks base method.
func (m *MockRetryStrategy) HandleRetry(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "HandleRetry", arg0)
}

// HandleRetry indicates an expected call of HandleRetry.
func (mr *MockRetryStrategyMockRecorder) HandleRetry(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleRetry", reflect.TypeOf((*MockRetryStrategy)(nil).HandleRetry), arg0)
}
