---

variables:
  WORKFLOW:
    value: default
    description: "Control pipeline workflow"
    options:
      - default
      - installers

stages:
  - test
  - build
  - installer

include:
  - local: /ci/setup.yml
  - local: /ci/test.yml
  - local: /ci/build.yml
  - local: /ci/installers.yml
    rules:
      - if: $WORKFLOW == "installers"
      - if: $CI_COMMIT_TAG =~ /^et-\d+/
