---

build-linux:
  stage: build
  variables:
    ARCHIVE_NAME: $ARCHIVE_NAME_LINUX
  extends:
    - .env-linux-build
  script:
    - !reference [.script-config-git, script]
    - !reference [.script-config-cmake-unix, script]
    - !reference [.script-test, script]
    - !reference [.script-install, script]
    - tar -czf $CMAKE_INSTALL_DIR/$ARCHIVE_NAME -C $CMAKE_INSTALL_DIR/bin $ET_BIN_NAME $ET_DLL_NAME.so
  artifacts:
    name: linux_x86_64
    paths:
      - $CMAKE_INSTALL_DIR/$ARCHIVE_NAME
      - $CMAKE_INSTALL_DIR/meta/version.json
    when: always
    expire_in: 4 hrs

build-darwin-arm64:
  variables:
    CMAKE_INSTALL_DIR: $CMAKE_INSTALL_DIR_MACOS_ARM64
  stage: build
  extends:
    - .env-darwin
  script:
    - !reference [.script-config-git, script]
    - !reference [.script-config-cmake-macos-arm64, script]
    - !reference [.script-test, script]
    - !reference [.script-install, script]
  artifacts:
    paths:
      - $CMAKE_INSTALL_DIR
    when: always
    expire_in: 4 hrs

build-darwin-x86_64:
  variables:
    CMAKE_INSTALL_DIR: $CMAKE_INSTALL_DIR_MACOS_X64
  stage: build
  extends:
    - .env-darwin
  script:
    - !reference [.script-config-git, script]
    - !reference [.script-config-cmake-macos-x86_64, script]
    - !reference [.script-build, script]
    - !reference [.script-install, script]
  artifacts:
    paths:
      - $CMAKE_INSTALL_DIR
    when: always
    expire_in: 4 hrs

build-darwin-universal:
  stage: build
  needs: ["build-darwin-x86_64", "build-darwin-arm64"]
  extends:
    - .env-darwin
  variables:
    CMAKE_INSTALL_DIR: $CMAKE_INSTALL_DIR_MACOS_UNIVERSAL
    ARCHIVE_NAME: $ARCHIVE_NAME_MACOS
    APP_NAME: "${ET_BIN_NAME}.app"
  script:
    - ./scripts/create_app_darwin.sh
      $CMAKE_INSTALL_DIR/${ARCHIVE_NAME}
      $APP_NAME
      $CMAKE_INSTALL_DIR_MACOS_ARM64/meta
      $CMAKE_INSTALL_DIR_MACOS_ARM64/bin
      $CMAKE_INSTALL_DIR_MACOS_X64/bin
  artifacts:
    name: mac_app
    paths:
      - $CMAKE_INSTALL_DIR/$ARCHIVE_NAME
    when: always
    expire_in: 4 hrs

build-windows:
  stage: build
  variables:
    ARCHIVE_NAME: $ARCHIVE_NAME_WINDOWS
    # Need to change the CMAKE_INSTALL_DIR because CI_PROJECT_NAME doesn't
    # contain C:\ prefix. It is considered relative path by pwsh and packing
    # job would need complex path to find artifacts.
    CMAKE_INSTALL_DIR: ./cmake-install-release
  extends:
    - .env-windows
  script:
    - !reference [.script-config-git, script]
    - !reference [.script-config-cmake-win, script]
    - !reference [.script-test, script]
    - !reference [.script-install, script]
    - Push-Location "$CMAKE_INSTALL_DIR/bin"
    - Compress-Archive -DestinationPath "$ARCHIVE_NAME" -Path "$ET_BIN_NAME.exe","$ET_DLL_NAME.dll"
    - Pop-Location
  artifacts:
    name: windows_x86_64
    paths:
      - $CMAKE_INSTALL_DIR/bin/$ARCHIVE_NAME
    when: always
    expire_in: 4 hrs
