version: "2"
linters:
  default: none
  enable:
    - asciicheck
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - exhaustive
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - gomodguard
    - goprintffuncname
    - gosec
    - govet
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
  settings:
    godox:
      keywords:
        - TODO
        - FIXME
  exclusions:
    generated: lax
    rules:
      - linters:
          - dogsled
          - dupl
          - gochecknoglobals
          - gochecknoinits
          - goconst
          - gosec
        path: _test\.go
      - path: (.+)\.go$
        text: Using the variable on range scope `tt` in function literal
      - path: (.+)\.go$
        text: should have comment (\([^)]+\) )?or be unexported
      - path: (.+)\.go$
        text: at least one file in a package should have a package comment
      - path: (.+)\.go$
        text: 'package-comments: should have a package comment'
      - path: (.+)\.go$
        text: 'var-naming: don''t use underscores in Go names'
      - path: (.+)\.go$
        text: 'ST1003: should not use underscores in Go names'
    paths:
      - internal/constants.go
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/constants.go
      - third_party$
      - builtin$
      - examples$
